### ISSUE TITLE
Building this doesn't allow inject into iTunes

### ISSUE THREAD

**Issue by ghost** [w0lfschild/iTunesPlus#1]
I've built this using the available source code but just can't get it to inject into iTunes on High Sierra.

The output was a fine bundle for SIMBL - Xcode even put it right where it should be.

Can you make it work with your developer skills? The Download Latest Release on iTunesPlus' repo doesn't lead anywhere.

**Comment by w0lfschild** [comment]
You need to turn off AMFI and SIP for iTunes to load plugins.

**Comment by ghost** [comment]
That's odd then - because, ever since I installed the updated version of mySIMBL I turned off AMFI too. Let me try this whole thing again. Thanks.
