### ISSUE TITLE
iTunesPlus Bundle Download Link - 404 Page Not Found

### ISSUE THREAD

**Issue by Machaan** [w0lfschild/iTunesPlus#2]
Hi w0lfschild,
First, I wanted to say that I love your work and really appreciate the work you have done with mySIMBL, etc. I had a quick question though-- is there a iTunesPlus.bundle release available for download or am I supposed to compile it with XCode? Whenever I click the iTunesPlus link in the installation instructions, it takes me to a webpage saying: 404 Page Not Found.

Thanks!

**Comment by w0lfschild** [comment]
Sorry for the really long delay. The link is fixed and a compiled build is available for download.
