### ISSUE TITLE
Bottom margin and iTunes icon customization

### ISSUE THREAD

**Issue by InDoubt** [w0lfschild/iTunesPlus#4]
Thank you for developing this wonderful customization tool for the dock!
I wonder if it is posible to set the dock (background and icons) about 25 to 30 px separation from the bottom.
Also if there is a way (for a neophyte) to make the iTunes Playing Now icon round corners (clipping the image corners) with an adjustable size, so it matches my dock icons scheme.
Thank you!
![dockfantastic](https://user-images.githubusercontent.com/17437998/49941258-fcdeec80-feaf-11e8-8533-9314f55e7e23.jpg)
![itunesicon](https://user-images.githubusercontent.com/17437998/49941273-023c3700-feb0-11e8-817c-e6d9c4658a26.gif)

**Comment by w0lfschild** [comment]
You could probably replace one of the overlay files in the bundles content with one that matches your theme.

**Comment by InDoubt** [comment]
Thank you, w0lfschild!
Are you referring to increasing the separation between the dock background and the bottom edge of the screen or changing the shape of the iTunes icon playing?
Where are exactly those bundles to tweak? I have all I can "show package content"-ed to no avail.
Thank you for your guidance!

**Comment by InDoubt** [comment]
Regarding the icon shape to match the others icons, I've found iTunesPlus.bundle>Content>Resources>xxx.Overlay.png
I made one to replace ClassicOverlay.png with the shape I want but it doesn't work.
See pic.
Could you give some advice, please.
(as for the dock background I still don't know what to do) 
![Screen Shot 2019-08-10 at 3 06 26 PM](https://user-images.githubusercontent.com/17437998/62825943-e3e32400-bb81-11e9-9903-d263846b42c6.jpg)

**Comment by w0lfschild** [comment]
Hmmm. I just realized I was manually making them circular not masking them to the overlay.

I'll put out a new version with another option that uses a mask.

**Comment by w0lfschild** [comment]
New version [2.1](https://github.com/w0lfschild/iTunesPlus/blob/master/build/iTunesPlus.bundle.zip)

This has a 5th drawing option `Rounded Corners`

This uses `../iTunesPlus.bundle/Contents/Resources/NewOverlay.png`

You can make any black pattern on a white background and the artwork will draw only what would fall in the black area.

EG:

Album Artwork
![1](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Art/two_tigers.gif)

Mask image
![2](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Art/two_tiger_mask.gif)

Result
![3](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Art/image_create_w_mask.gif)

**Comment by InDoubt** [comment]
Thank you so much, w0lfschild!
![Screen Shot 2019-08-10 at 7 16 04 PM](https://user-images.githubusercontent.com/17437998/62827740-57495d80-bba3-11e9-9628-378d9c39de2a.jpg)
